### ISSUE TITLE
Divination Card Typo

### ISSUE THREAD

**Issue by GlenCFL** [SpacetimeDensityModifier/Spirit_Filter#1]
You've misspelled the divination card "The Cacophony" as "The Cacaphony".

The original announcement is [here](https://www.pathofexile.com/forum/view-thread/2197836).
It's also spelled this way in the item filter data [here](https://www.pathofexile.com/forum/view-thread/2201188/).

**Comment by GlenCFL** [comment]
@SpacetimeDensityModifier

**Comment by SpacetimeDensityModifier** [comment]
RIP me. Thanks
